site_name: Yuk Helper Reference
site_url: https://www.yukdiorder.com/
nav:
    - Home: index.md
    - Classes: classes.md
theme: readthedocs
markdown_extensions:
    - toc:
        permalink: "#"
        separator: "_"